//! Cache of generated fixture profiles in `target/fixtures-cache` (SPEC-12 §4.3).
//!
//! A profile is generated once per content key into `<name>-<key>` and then
//! copied. Generation goes to a temporary folder next to it that is renamed
//! into place, so concurrent test processes never see a partial profile: the
//! loser of a race discards its copy.

use std::fs;
use std::path::{Path, PathBuf};

use crate::fixture::ProfileSpec;

/// Changes whenever the generator produces different files for the same description.
const GENERATOR_VERSION: &str = "sk-testkit fixtures v1";

/// Content key of a profile: a hash of the generator version, the description
/// and the samples it uses.
pub(crate) fn key(src: &str, spec: &ProfileSpec, samples: &Path) -> Result<String, String> {
    let mut hasher = blake3::Hasher::new();
    update_framed(&mut hasher, GENERATOR_VERSION.as_bytes());
    update_framed(&mut hasher, src.as_bytes());
    for name in spec.samples() {
        let path = samples.join(name);
        let data =
            fs::read(&path).map_err(|e| format!("cannot read sample {}: {e}", path.display()))?;
        update_framed(&mut hasher, name.as_bytes());
        update_framed(&mut hasher, &data);
    }
    Ok(hasher.finalize().to_hex()[..16].to_owned())
}

/// Length-prefixed, so that different splits of the same bytes hash differently.
fn update_framed(hasher: &mut blake3::Hasher, data: &[u8]) {
    hasher.update(&(data.len() as u64).to_le_bytes());
    hasher.update(data);
}

/// The cached folder of profile `name` with content `key`, generated by
/// `generate` if missing. `Ok(None)` if the cache folder cannot be used.
pub(crate) fn get_or_create(
    name: &str,
    key: &str,
    generate: impl FnOnce(&Path) -> Result<(), String>,
) -> Result<Option<PathBuf>, String> {
    let cache = cache_dir();
    let done = cache.join(format!("{name}-{key}"));
    if done.is_dir() {
        return Ok(Some(done));
    }
    if fs::create_dir_all(&cache).is_err() {
        return Ok(None);
    }
    let Ok(tmp) = tempfile::Builder::new()
        .prefix(&format!(".tmp-{name}-"))
        .tempdir_in(&cache)
    else {
        return Ok(None);
    };
    generate(tmp.path())?;
    match fs::rename(tmp.path(), &done) {
        Ok(()) => {
            // Already moved: nothing to delete.
            let _ = tmp.keep();
            Ok(Some(done))
        }
        // Another process won the race; `tmp` is deleted on drop.
        Err(_) if done.is_dir() => Ok(Some(done)),
        Err(e) => Err(format!(
            "cannot move {} to {}: {e}",
            tmp.path().display(),
            done.display()
        )),
    }
}

/// `<target>/fixtures-cache`; `<target>` is an absolute `CARGO_TARGET_DIR`
/// or the workspace `target` folder.
fn cache_dir() -> PathBuf {
    let target = std::env::var_os("CARGO_TARGET_DIR")
        .map(PathBuf::from)
        .filter(|p| p.is_absolute())
        .unwrap_or_else(|| {
            Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("..")
                .join("..")
                .join("target")
        });
    target.join("fixtures-cache")
}
